### PR TITLE
RHOAIENG-14150: Upgrade the x/net package v0.23.0

### PR DESCRIPTION
**Pull request by dibryant**
Fixes for https://issues.redhat.com/browse/RHOAIENG-14150

Upgrade the x/net package v0.23.0 for the CVE fix.

### CODE REVIEW

**Comment by jstourac** [comment]
/lgtm

Thank you!

**Comment by jiridanek** [comment]
/lgtm
too

**Comment by jiridanek** [comment]
old branch, I see; here only @atheo89 and @harshad16 can command The Prow to Merge

**Comment by jiridanek** [comment]
I'll twist the magic Red Hat and merge this anyways!

**Pull request merged**
