### PR TITLE
Update Dockerfile.konflux

### PR DESCRIPTION
**Pull request by MohammadiIram**

### CODE REVIEW

**Comment by MohammadiIram** [comment]
@atheo89 @jiridanek Could you please review this PR?

**Comment by jstourac** [comment]
Would it be possible to introduce some reasonable commit messages and PR descriptions for changes like this?

**Comment by jiridanek** [comment]
> Would it be possible to introduce some reasonable commit messages and PR descriptions for changes like this?

Ask WatsonX ;P

> In the commits pane, select the commit or several commits you want to summarize, right-click them and select Explain Commit with AI Assistant in the context menu. AI Assistant provides the summary of the selected commits.

https://www.jetbrains.com/help/idea/work-with-commits.html#ai-explain-commit

**Pull request merged**
