### PR TITLE
fix: patch images of notebook-controller in its components

### PR DESCRIPTION
**Pull request by harshad16**
patch images of notebook-controller in its components
Related-to: https://github.com/opendatahub-io/opendatahub-operator/issues/579

Moved patch of images in `component/base` to:
1. notebook-controller: `components/notebook-controller/config/overlays/openshift/`
2. odh-notebook-controller: `components/odh-notebook-controller/config/base`

### CODE REVIEW

**Comment by zdtsw** [comment]
failed tests are not related to change:
/go/pkg/mod/go.uber.org/zap@v1.26.0/internal/pool/pool.go:40:6: too many errors
note: module requires Go 1.19
```
# go.uber.org/multierr
/go/pkg/mod/go.uber.org/multierr@v1.10.0/error.go:224:13: undefined: atomic.Bool
note: module requires Go 1.19
Go compliance shim [11305] [][]: Exited with: 2
```

**Review by zdtsw — APPROVED** [review]
/lgtm

**Review by zdtsw — APPROVED** [review]
/lgtm

**Comment by harshad16** [comment]
Thanks for the review.
/approve

**Pull request merged**
