### PR TITLE
[master] sync the master branch with upstream opendatahub stable branch

### PR DESCRIPTION
**Pull request by harshad16**
[master] sync the master branch with upstream opendatahub stable branch

### CODE REVIEW

**Comment by harshad16** [comment]
Merging to get the sprint end ready.
Thanks

**Comment by jiridanek** [comment]
@harshad16 I think we need to do vvv also for the red-hat-data-services fork of the repo

* https://github.com/openshift/release/pull/52888

**Comment by jstourac** [comment]
The integration test failed with:
```
  Warning  InspectFailed  1s (x10 over 101s)  kubelet            Failed to apply default image tag "$(odh-notebook-controller-image)": couldn't parse image reference "$(odh-notebook-controller-image)": invalid reference format
```
Is this expected?

**Comment by harshad16** [comment]
> The integration test failed with:
> 
> ```
>   Warning  InspectFailed  1s (x10 over 101s)  kubelet            Failed to apply default image tag "$(odh-notebook-controller-image)": couldn't parse image reference "$(odh-notebook-controller-image)": invalid reference format
> ```
> 
> Is this expected?

Definitely not expected, checking on it

**Comment by jiridanek** [comment]
> Definitely not expected, checking on it

The `kubectl describe` on the pod has

```
Containers:
  manager:
    Container ID:  
    Image:         $(odh-notebook-controller-image)
```

so it looks like the image placeholder is different in red-hat-data-services from what it was in opendatahub-io, and the code to do the replacement that worked in opendatahub-io does not work here

```
+ kustomize edit set image quay.io/opendatahub/odh-notebook-controller:latest=localhost/odh-notebook-controller:integration-test
```

**Comment by jiridanek** [comment]
The difference between opendatahub-io and red-hat-data-services was introduced in

* #28

**Comment by harshad16** [comment]
This is all set,  going to merge this and
fix the breaking Test in subsequent PR.
:+1: , thanks all

**Pull request merged**
