### PR TITLE
RHOAIENG-14150: Upgrade the x/net package v0.23.0 

### PR DESCRIPTION
**Pull request by dibryant**
Fixes for https://issues.redhat.com/browse/RHOAIENG-14150

Upgrade the x/net package v0.23.0 for the CVE fix.

### CODE REVIEW

**Comment by jiridanek** [comment]
I don't understand the ci fail. Let's see a rerun, maybe I'll wake up to a passing build tomorrow.

/retest

**Comment by harshad16** [comment]
> I don't understand the ci fail. Let's see a rerun, maybe I'll wake up to a passing build tomorrow.
> 

The problem seems to be , first the PR was opened to master, so the ci are executing all under assumption of master
instead of rhoai-2.10, which causes the conflict issue.
however interesting that retest command is also taking the ci to same configuration .

**Comment by dibryant** [comment]
recreating the PR

**Pull request closed without merging**
